/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMarketPricesRouteImport } from './routes/dashboard/market-prices'
import { Route as DashboardFarmMapRouteImport } from './routes/dashboard/farm-map'
import { Route as DashboardDiseaseScanRouteImport } from './routes/dashboard/disease-scan'
import { Route as DashboardCropAdvisorRouteImport } from './routes/dashboard/crop-advisor'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard/ai-assistant'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketPricesRoute = DashboardMarketPricesRouteImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFarmMapRoute = DashboardFarmMapRouteImport.update({
  id: '/farm-map',
  path: '/farm-map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiseaseScanRoute = DashboardDiseaseScanRouteImport.update({
  id: '/disease-scan',
  path: '/disease-scan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCropAdvisorRoute = DashboardCropAdvisorRouteImport.update({
  id: '/crop-advisor',
  path: '/crop-advisor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/crop-advisor': typeof DashboardCropAdvisorRoute
  '/dashboard/disease-scan': typeof DashboardDiseaseScanRoute
  '/dashboard/farm-map': typeof DashboardFarmMapRoute
  '/dashboard/market-prices': typeof DashboardMarketPricesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/crop-advisor': typeof DashboardCropAdvisorRoute
  '/dashboard/disease-scan': typeof DashboardDiseaseScanRoute
  '/dashboard/farm-map': typeof DashboardFarmMapRoute
  '/dashboard/market-prices': typeof DashboardMarketPricesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/crop-advisor': typeof DashboardCropAdvisorRoute
  '/dashboard/disease-scan': typeof DashboardDiseaseScanRoute
  '/dashboard/farm-map': typeof DashboardFarmMapRoute
  '/dashboard/market-prices': typeof DashboardMarketPricesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/ai-assistant'
    | '/dashboard/crop-advisor'
    | '/dashboard/disease-scan'
    | '/dashboard/farm-map'
    | '/dashboard/market-prices'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/ai-assistant'
    | '/dashboard/crop-advisor'
    | '/dashboard/disease-scan'
    | '/dashboard/farm-map'
    | '/dashboard/market-prices'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/ai-assistant'
    | '/dashboard/crop-advisor'
    | '/dashboard/disease-scan'
    | '/dashboard/farm-map'
    | '/dashboard/market-prices'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/market-prices': {
      id: '/dashboard/market-prices'
      path: '/market-prices'
      fullPath: '/dashboard/market-prices'
      preLoaderRoute: typeof DashboardMarketPricesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/farm-map': {
      id: '/dashboard/farm-map'
      path: '/farm-map'
      fullPath: '/dashboard/farm-map'
      preLoaderRoute: typeof DashboardFarmMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/disease-scan': {
      id: '/dashboard/disease-scan'
      path: '/disease-scan'
      fullPath: '/dashboard/disease-scan'
      preLoaderRoute: typeof DashboardDiseaseScanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crop-advisor': {
      id: '/dashboard/crop-advisor'
      path: '/crop-advisor'
      fullPath: '/dashboard/crop-advisor'
      preLoaderRoute: typeof DashboardCropAdvisorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardCropAdvisorRoute: typeof DashboardCropAdvisorRoute
  DashboardDiseaseScanRoute: typeof DashboardDiseaseScanRoute
  DashboardFarmMapRoute: typeof DashboardFarmMapRoute
  DashboardMarketPricesRoute: typeof DashboardMarketPricesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardCropAdvisorRoute: DashboardCropAdvisorRoute,
  DashboardDiseaseScanRoute: DashboardDiseaseScanRoute,
  DashboardFarmMapRoute: DashboardFarmMapRoute,
  DashboardMarketPricesRoute: DashboardMarketPricesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
